[project]
name = "knwiki"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bogdan", email = "github.34373732@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
knwiki = "knwiki:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "zensical>=0.0.63",
]
